# Build the container
# docker build --tag folivetti/manylinux2014_ghc965_i686 --file Dockerfile.manylinux2014_ghc9121_i686 .
FROM quay.io/pypa/musllinux_1_1_x86_64

# Install prerequisites
RUN apk add gmp-dev
RUN apk add ncurses ncurses-dev

# Install GHC and Cabal
RUN ln -s "/usr/local/bin/python3.12" "/usr/local/bin/python3"
RUN python3 -m pip install wget==3.2
RUN python3 -c "import wget; wget.download('https://raw.githubusercontent.com/folivetti/ghc_docker/refs/heads/main/install_ghc_x86_musl.bash', '/tmp/install_ghc_x86_musl.bash')"
RUN chmod +x /tmp/install_ghc_x86_musl.bash
RUN /tmp/install_ghc_x86_musl.bash 9.12.1
