# Build the container
# docker build --tag folivetti/manylinux2014_ghc965_i686 --file Dockerfile.manylinux2014_ghc9121_i686 .
FROM quay.io/pypa/manylinux2014_i686

# Install prerequisites
RUN yum install -y gmp-devel ncurses-devel

# Install GHC and Cabal
RUN ln -s "/usr/local/bin/python3.12" "/usr/local/bin/python3"
RUN python3 -m pip install wget==3.2
RUN python3 -c "import wget; wget.download('https://raw.githubusercontent.com/folivetti/ghc_docker/refs/heads/main/install_ghc_i686.bash', '/tmp/install_ghc_i686.bash')"
RUN chmod +x /tmp/install_ghc_i686.bash
RUN /tmp/install_ghc_i686.bash 9.12.1
