# Build the container
# docker build --tag folivetti/manylinux2014_ghc965_i686 --file Dockerfile.manylinux2014_ghc9121_i686 .
FROM quay.io/pypa/manylinux2014_x86_64

# Link libgmp.so.10 to libgmp.so
RUN ln -s "/usr/lib64/libgmp.so.10" "/usr/lib64/libgmp.so"

# Link libtinfo.so.6 to libtinfo.so
RUN ln -s "/usr/lib64/libtinfo.so.6" "/usr/lib64/libtinfo.so"

# Install prerequisites
RUN yum install -y gmp-devel ncurses-devel epel-release
RUN yum install -y nlopt nlopt-devel

# Install GHC and Cabal
RUN ln -s "/usr/local/bin/python3.12" "/usr/local/bin/python3"
RUN python3 -m pip install wget==3.2
RUN python3 -c "import wget; wget.download('https://raw.githubusercontent.com/folivetti/ghc_docker/refs/heads/main/install_ghc_x86.bash', '/tmp/install_ghc_x86.bash')"
RUN chmod +x /tmp/install_ghc_x86.bash
RUN /tmp/install_ghc_x86.bash 9.12.1
