# Build the container
# docker build --tag folivetti/manylinux2014_ghc965_i686 --file Dockerfile.manylinux2014_ghc9121_i686 .
FROM quay.io/pypa/manylinux2014_x86_64

# Link libgmp.so.10 to libgmp.so
RUN ln -s "/usr/lib64/libgmp.so.10" "/usr/lib64/libgmp.so"

# Link libtinfo.so.6 to libtinfo.so
RUN ln -s "/usr/lib64/libtinfo.so.6" "/usr/lib64/libtinfo.so"

# Install prerequisites
RUN yum install -y gmp-devel ncurses-devel

# Install GHC and Cabal
RUN ln -s "/usr/local/bin/python3.12" "/usr/local/bin/python3"
RUN python3 -m pip install wget==3.2
RUN python3 -c "import wget; wget.download('https://raw.githubusercontent.com/folivetti/ghc_docker/refs/heads/main/install_ghc_x86.bash', '/tmp/install_ghc_x86.bash')"
RUN chmod +x /tmp/install_ghc_x86.bash
RUN /tmp/install_ghc_x86.bash 9.12.1

# Install NLOpt
RUN python3.12 -c "import wget; wget.download('https://github.com/stevengj/nlopt/archive/v2.7.1.tar.gz', '/tmp/nlopt.tar.gz')"
RUN yum install -y cmake3
RUN (cd "/tmp" && tar zxvf nlopt.tar.gz)
RUN (mv "/tmp/nlopt-2.7.1" "/tmp/nlopt")
RUN (cd "/tmp/nlopt" && cmake3 . && make && make install)
RUN (echo export LIBRARY_PATH="/usr/local/lib64:$LIBRARY_PATH" >> ~/.bashrc)
RUN (echo export LD_LIBRARY_PATH="/usr/local/lib64:$LD_LIBRARY_PATH" >> ~/.bashrc)
RUN (echo export C_INCLUDE_PATH="/usr/local/include:$C_INCLUDE_PATH" >> ~/.bashrc)
RUN (echo export PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig:$PKG_CONFIG_PATH" >> ~/.bashrc)
